#!/bin/bash

# 更新和安装依赖
install_dependencies() {
  echo "检查并安装系统软件包和依赖..."
  sudo apt update && sudo apt upgrade -y
  if [ $? -ne 0 ]; then
    echo "更新系统软件包时出错" >> error.log
    exit 1
  fi
  sudo apt install -y clang pkg-config libssl-dev curl git wget htop tmux build-essential jq make lz4 gcc unzip gawk bison
  if [ $? -ne 0 ]; then
    echo "安装依赖时出错" >> error.log
    exit 1
  fi
}

# 安装 GLIBC 2.34
install_glibc() {
  echo "安装 GLIBC 2.34..."
  mkdir -p $HOME/glibc-2.34
  cd $HOME/glibc-2.34
  wget http://ftp.gnu.org/gnu/libc/glibc-2.34.tar.gz
  if [ $? -ne 0 ]; then
    echo "下载 GLIBC 2.34 时出错" >> error.log
    exit 1
  fi
  tar -xvzf glibc-2.34.tar.gz
  cd glibc-2.34
  mkdir build
  cd build
  ../configure --prefix=$HOME/glibc-2.34
  make
  if [ $? -ne 0 ]; then
    echo "编译 GLIBC 2.34 时出错" >> error.log
    exit 1
  fi
  make install
  if [ $? -ne 0 ]; then
    echo "安装 GLIBC 2.34 时出错" >> error.log
    exit 1
  fi
  export LD_LIBRARY_PATH=$HOME/glibc-2.34/lib:$LD_LIBRARY_PATH
}

# 检查并安装 Go
install_go() {
  if ! command -v go &> /dev/null
  then
    echo "安装 Go..."
    cd $HOME
    sudo rm -rf /usr/local/go
    if [ $? -ne 0 ]; then
      echo "删除旧版本 Go 时出错" >> error.log
      exit 1
    fi
    echo "下载 Go 安装包..."
    curl -# -L https://go.dev/dl/go1.21.7.linux-amd64.tar.gz -o go1.21.7.linux-amd64.tar.gz
    if [ $? -ne 0 ]; then
      echo "下载 Go 安装包时出错" >> error.log
      exit 1
    fi
    sudo tar -xzf go1.21.7.linux-amd64.tar.gz -C /usr/local
    if [ $? -ne 0 ]; then
      echo "解压 Go 安装包时出错" >> error.log
      exit 1
    fi
    rm go1.21.7.linux-amd64.tar.gz
    eval $(echo 'export PATH=$PATH:/usr/local/go/bin' | sudo tee /etc/profile.d/golang.sh)
    eval $(echo 'export PATH=$PATH:$HOME/go/bin' | tee -a $HOME/.profile)
    source /etc/profile.d/golang.sh
    source $HOME/.profile
    go version
    if [ $? -ne 0 ]; then
      echo "安装 Go 失败" >> error.log
      exit 1
    fi
  else
    echo "Go 已安装，跳过安装步骤..."
  fi
}

# 设置变量
set_vars() {
  read -p "请输入你的节点名称 (MONIKER): " MONIKER
  echo "export MONIKER=$MONIKER" >> $HOME/.bash_profile
  echo "export AIR_CHAIN_ID=\"junction\"" >> $HOME/.bash_profile
  echo "export AIR_CHAIN_PORT=\"38\"" >> $HOME/.bash_profile
  source $HOME/.bash_profile
}

# 下载并配置二进制文件
setup_binary() {
  echo "下载并配置二进制文件..."
  if [ ! -f /usr/local/bin/junctiond ]; then
    wget https://github.com/airchains-network/junction/releases/download/v0.1.0/junctiond
    if [ $? -ne 0 ];then
      echo "下载 junctiond 时出错" >> error.log
      exit 1
    fi
    chmod +x junctiond
    sudo mv junctiond /usr/local/bin
  else
    echo "junctiond 已安装，跳过安装步骤..."
  fi
}

# 初始化应用程序
init_app() {
  echo "初始化应用程序..."
  if [ ! -d "$HOME/.junction" ]; then
    junctiond init $MONIKER --chain-id $AIR_CHAIN_ID
    if [ $? -ne 0 ];then
      echo "初始化应用程序时出错" >> error.log
      exit 1
    fi
  fi
  wget -O $HOME/.junction/config/genesis.json https://testnet-files.syanodes.my.id/airchain-genesis.json
  if [ $? -ne 0 ];then
    echo "下载 genesis.json 时出错" >> error.log
    exit 1
  fi
  wget -O $HOME/.junction/config/addrbook.json https://testnet-files.syanodes.my.id/airchain-addrbook.json
  if [ $? -ne 0 ];then
    echo "下载 addrbook.json 时出错" >> error.log
    exit 1
  fi
}

# 配置种子和对等节点
configure_peers() {
  echo "配置种子和对等节点..."
  SEEDS="1918bd71bc764c71456d10483f754884223959a5@35.240.206.208:26656"
  PERSISTENT_PEERS="1918bd71bc764c71456d10483f754884223959a5@35.240.206.208:26656,8b72b2f2e027f8a736e36b2350f6897a5e9bfeaa@131.153.232.69:26656"
  sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/" \
         -e "s/^persistent_peers *=.*/persistent_peers = \"$PERSISTENT_PEERS\"/" \
         -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.0001amf\"/" \
         -e 's|^indexer *=.*|indexer = "null"|' \
         -e 's|^prometheus *=.*|prometheus = true|' \
         -e 's|^pex *=.*|pex = false|' $HOME/.junction/config/config.toml
}

# 配置修剪设置
configure_pruning() {
  echo "配置修剪设置..."
  pruning="custom"
  pruning_keep_recent="100"
  pruning_keep_every="0"
  pruning_interval="19"
  sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.junction/config/app.toml
  sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.junction/config/app.toml
  sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.junction/config/app.toml
  sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.junction/config/app.toml
}

# 配置自定义端口
configure_ports() {
  echo "配置自定义端口..."
  sed -i.bak -e "s%:1317%:${AIR_CHAIN_PORT}317%g;
  s%:8080%:${AIR_CHAIN_PORT}080%g;
  s%:9090%:${AIR_CHAIN_PORT}090%g;
  s%:9091%:${AIR_CHAIN_PORT}091%g;
  s%:8545%:${AIR_CHAIN_PORT}545%g;
  s%:8546%:${AIR_CHAIN_PORT}546%g;
  s%:6065%:${AIR_CHAIN_PORT}065%g" $HOME/.junction/config/app.toml
  sed -i.bak -e "s%:26658%:${AIR_CHAIN_PORT}658%g;
  s%:26657%:${AIR_CHAIN_PORT}657%g;
  s%:6060%:${AIR_CHAIN_PORT}060%g;
  s%:26656%:${AIR_CHAIN_PORT}656%g;
  s%^external_address = \"\"%external_address = \"$(wget -qO- eth0.me):${AIR_CHAIN_PORT}656\"%;
  s%:26660%:${AIR_CHAIN_PORT}660%g" $HOME/.junction/config/config.toml
  sed -i \
    -e 's|^chain-id *=.*|chain-id = "junction"|' \
    -e 's|^keyring-backend *=.*|keyring-backend = "test"|' \
    -e 's|^node *=.*|node = "tcp://localhost:38657"|' \
    $HOME/.junction/config/client.toml
}

# 设置服务文件
setup_service() {
  echo "设置服务文件..."
  sudo tee /etc/systemd/system/junctiond.service > /dev/null <<EOF
[Unit]
Description=airchain-testnet
After=network-online.target

[Service]
User=$USER
ExecStart=$(which junctiond) start --home $HOME/.junction --log_level debug --log_format json --minimum-gas-prices=0.01amf
Restart=on-failure
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

  sudo systemctl daemon-reload
  sudo systemctl enable junctiond
  sudo systemctl start junctiond
  if [ $? -ne 0 ];then
    echo "启动 junctiond 服务时出错" >> error.log
    exit 1
  fi
  sudo journalctl -fu junctiond -o cat
}

# 停止并重置节点
reset_node() {
  echo "停止并重置节点..."
  sudo systemctl stop junctiond
  if [ $? -ne 0 ];then
    echo "停止 junctiond 服务时出错" >> error.log
    exit 1
  fi
  cp $HOME/.junction/data/priv_validator_state.json $HOME/.junction/priv_validator_state.json.backup
  rm -rf $HOME/.junction/data
  junctiond tendermint unsafe-reset-all --home $HOME/.junction
  if [ $? -ne 0 ];then
    echo "重置节点时出错" >> error.log
    exit 1
  fi
}

# 配置状态同步
configure_state_sync() {
  echo "配置状态同步..."
  PERSISTENT_PEERS="1918bd71bc764c71456d10483f754884223959a5@35.240.206.208:26656,8b72b2f2e027f8a736e36b2350f6897a5e9bfeaa@131.153.232.69:26656"
  SNAP_RPC="https://airchains-testnet-rpc.crouton.digital/"
  sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$PERSISTENT_PEERS\"/" $HOME/.junction/config/config.toml

  LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height)
  if [ $? -ne 0 ];then
    echo "获取最新区块高度时出错" >> error.log
    exit 1
  fi
  BLOCK_HEIGHT=$((LATEST_HEIGHT - 1000))
  TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)
  if [ $? -ne 0 ];then
    echo "获取信任区块哈希时出错" >> error.log
    exit 1
  fi

  echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH && sleep 2

  sed -i.bak -E "s|^(enable[[:space:]]+=[[:space:]]+).*$|\1true| ;
  s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ;
  s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ;
  s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"| ;
  s|^(seeds[[:space:]]+=[[:space:]]+).*$|\1\"\"|" $HOME/.junction/config/config.toml

  mv $HOME/.junction/priv_validator_state.json.backup $HOME/.junction/data/priv_validator_state.json

  sudo systemctl restart junctiond
  if [ $? -ne 0 ];then
    echo "重启 junctiond 服务时出错" >> error.log
    exit 1
  fi
  sudo journalctl -u junctiond -f --no-hostname -o cat
}

# 删除所有内容
cleanup() {
  echo "删除之前下载的所有内容..."
  sudo systemctl stop junctiond
  if [ $? -ne 0 ];then
    echo "停止 junctiond 服务时出错" >> error.log
  fi
  sudo systemctl disable junctiond
  sudo rm /etc/systemd/system/junctiond.service
  sudo systemctl daemon-reload
  sudo rm -rf /usr/local/bin/junctiond $HOME/.junction $HOME/go /usr/local/go
  rm -rf $HOME/glibc-2.34
}

# 菜单选项
menu() {
  echo "1. 安装节点"
  echo "2. 删除之前下载的所有内容"
  echo "3. 钱包管理"
  echo "4. 验证者管理"
  echo "5. 代币管理"
  echo "6. 治理"
  echo "7. 服务管理"
  echo "8. 公用事业"
  echo "9. 退出"
  read -p "请选择一个选项: " choice

  case $choice in
    1)
      install_dependencies
      install_glibc
      install_go
      set_vars
      setup_binary
      init_app
      configure_peers
      configure_pruning
      configure_ports
      setup_service
      reset_node
      configure_state_sync
      ;;
    2)
      cleanup
      ;;
    3)
      echo "钱包管理选项"
      # 钱包管理选项逻辑
      ;;
    4)
      echo "验证者管理选项"
      # 验证者管理选项逻辑
      ;;
    5)
      echo "代币管理选项"
      # 代币管理选项逻辑
      ;;
    6)
      echo "治理选项"
      # 治理选项逻辑
      ;;
    7)
      echo "服务管理选项"
      # 服务管理选项逻辑
      ;;
    8)
      echo "公用事业选项"
      # 公用事业选项逻辑
      ;;
    9)
      exit 0
      ;;
    *)
      echo "无效选项，请重试。"
      menu
      ;;
  esac
}

# 显示菜单
menu
















